let gardenList = {
    "aridgarden": [
        "cactusfruit",
        "agave",
        "sisal",
        "cassava",
        "chickpea",
        "lentil",
        "minecraft:cactus"
    ],

    "frostgarden": [
        "raspberry",
        "oats",
        "rye",
        "celery",
        "peas",
        "beet",
        "rutabaga",
        "broccoli",
        "cauliflower",
        "cabbage",
        "spinach",
        "cotton",
        "huckleberry",
        "kohlrabi",
        "quinoa",
        "juniper"
    ],

    "shadedgarden": [
        "whitemushroom",
        "blackberry",
        "zucchini",
        "radish",
        "rhubarb",
        "tealeaf",
        "garlic",
        "sweetpotato",
        "turnip",
        "spiceleaf",
        "bean",
        "leek",
        "scallion",
        "tomato",
        "jute"
    ],

    "soggygarden": [
        "brusselsprout",
        "spiceleaf",
        "blueberry",
        "asparagus",
        "cranberry",
        "rice",
        "seaweed",
        "waterchestnut",
        "okra",
        "cotton",
        "kale",
        "millet",
        "jicama",
        "greengrape",
        "mulberry",
        "tomatillo"
    ],

    "tropicalgarden": [
        "grape",
        "pineapple",
        "kiwi",
        "sesameseeds",
        "curryleaf",
        "bambooshoot",
        "cantaloupe",
        "ginger",
        "coffeebean",
        "soybean",
        "eggplant",
        "kenaf",
        "arrowroot",
        "taro"
    ],

    "windygarden": [
        "strawberry",
        "barley",
        "corn",
        "cucumber",
        "wintersquash",
        "mustardseeds",
        "onion",
        "parsnip",
        "peanut",
        "minecraft:potato",
        "minecraft:carrot",
        "lettuce",
        "artichoke",
        "bellpepper",
        "chilipepper",
        "minecraft:wheat",
        "flax",
        "amaranth",
        "elderberry"
    ]
};