# This is a basic workflow to help you get started with Actions

name: Make mod file

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  make_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- uses: montudor/action-zip@v0.1.0
        #with:
        #  args: zip -qq -r Harvest-Craft-PE.zip Harvest-Craft-PE
      - uses: actions/upload-artifact@master
        with:
          name: modfile
          path: Harvest-Craft-PE
